Adds conversion rules for Gray and Color images wrapped by OffsetArray
JuliaImages/ImageCore.jl pull request #58
Opened 2018-05-25 14:08 UTC by zygmuntszpak

This contribution is a prerequisite for [adding OffsetArrays capability to gaussian_pyramid.](https://github.com/JuliaImages/Images.jl/pull/722)

2018-05-25 14:12 UTC, zygmuntszpak commented
@Evizero  @arijitkar98
This pull-request addresses the conversion issue that we encountered with  `OffsetArray` in the Gaussian pyramid pull-request.

2018-05-25 14:15 UTC, Evizero requested changes
Looks great!

Just some minor remarks concerning the tests

2018-05-25 14:15 UTC, Evizero commented on test/convert_reinterpret.jl
> +    @test eltype(s) == Gray{Float32}
could you also add this line to the tests

```julia
@test s isa OffsetArray{Gray{Float32},2,Array{Gray{Float32}}}
```

2018-05-25 14:15 UTC, Evizero commented on test/convert_reinterpret.jl
> +    imgo = OffsetArray(img, 0, 0)
probably would be a good idea to use something like `OffsetArray(img, -2, -1)` and then later test that the following is true

```julia
@test indices(s) === indices(imgo)
```

2018-05-25 14:15 UTC, Evizero commented on test/convert_reinterpret.jl
> +    imgo = OffsetArray(img, 0, 0)
I think it would help readability a little if the content of the `for` loop is indented

2018-05-25 14:20 UTC, Evizero commented
I changed the target branch to `release-0.6`, since we do want this changes in 0.6. We haven't quite yet made the hard distinction but we already somewhat started to diverge in terms of 0.6 and 0.7.

see conversation here https://github.com/JuliaImages/ImageCore.jl/pull/54#issuecomment-354303100

2018-05-25 17:33 UTC, Evizero commented
I see that changing the target branch caused github to think the previous two commits on `master` should also be merged into `release-0.6`, which it shouldn't.

It might be easier - and probably cleaner - to merge it into master after all, and then just backport the commit

2018-05-26 08:22 UTC, zygmuntszpak commented
I've incorporated all of the requested changes. Thanks for the great suggestions.

2018-05-26 10:55 UTC, Evizero approved these changes

2018-05-26 10:55 UTC, Evizero commented
Thanks!

2018-05-26 10:55 UTC, merged